### ISSUE TITLE
Multi-step prompts often fail

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#65]
Prompts that require preprocessing steps before plotting, such as:
- Remove "All Industries" from Industry name then plot a pie chart of sales by industry name
- Plot a bar chart of sales by industry name sorted descending
will often only do the prompt part of the instruction without the preprocessing

This was not an issue when we were using only PandasAI for both data manipulation and plotting

**Comment by thanhnew2001** [comment]
This stills works:
- Plot a bar chart of sales by industry name sorted descending
<img width="1407" alt="image" src="https://github.com/AlexandreSajus/TalkToTaipy/assets/3261272/c937911e-0c4f-4f63-b537-dc82b3dbc0bb">

**Comment by thanhnew2001** [comment]
This also stills work:
- Remove "USA" from country then plot a pie chart of sales by country

<img width="1387" alt="image" src="https://github.com/AlexandreSajus/TalkToTaipy/assets/3261272/387031a1-2855-4bd3-b06c-4e6296a7e1f6">
