### ISSUE TITLE
Initial dataset columns should be renamed

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#68]
Especially this one:
![image](https://github.com/AlexandreSajus/TalkToTaipy/assets/62465003/edacc188-de6a-4f60-9286-3c6a92928c0e)

**Comment by thanhnew2001** [comment]
This is actually beatified by a smart word recognized function. However, for acronym like this, maybe should be kept the same.

**Comment by AlexandreSajus** [comment]
Yeah, I will do a quick fix by just manually renaming the columns in the standard dataset
