### ISSUE TITLE
Data manipulation prompts that fail

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#71]
[dataset.csv](https://github.com/AlexandreSajus/TalkToTaipy/files/12560915/dataset.csv)

On this dataset, the following data manipulation prompts failed:
- List the unique car brands present in the dataset
- Average MinMpg

**Comment by thanhnew2001** [comment]
confirmed, will figure out why

**Comment by thanhnew2001** [comment]
I fixed this, it somehow skiped cases that were not df, value.
