### ISSUE TITLE
Prevent loading too large datasets

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#72]
A user in beta testing loaded a 100Mb dataset. The dataset got uploaded, but it froze the app indefinitely and needed a reset. We should limit the upload filesize

**Comment by thanhnew2001** [comment]
maybe 10MB? or a env variable for this?

**Comment by thanhnew2001** [comment]
I tried but failed we will need TaipyGUI Team to setup this for us. Current callback does not give us a chance to intercept the upload.

**Comment by AlexandreSajus** [comment]
Interesting, I'll ask for help

**Comment by AlexandreSajus** [comment]
Unfortunately, there is no way to restrict file size on upload yet with Taipy. We could do some things to check the size once it is uploaded; if it is too large, we will refuse it. It took a minute to upload in beta testing, but it did. It was loading it into a table that crashed the app.

**Comment by AlexandreSajus** [comment]
Could be a RAM issue on the Cloud machine as well

**Comment by AlexandreSajus** [comment]
Maybe we could show a pop-up before uploading the file to warn the user about the filesize limitaion

**Comment by AlexandreSajus** [comment]
Before reading with pandas, the app will check if the file is bigger than 20MB and will notify with an error if it is

I still need to check if this works fine on Cloud by testing with 1MB, 18MB, 22MB and 100MB datasets
