### ISSUE TITLE
Prompt Builder: histogram should not have two arguments

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#73]
A histogram can only take one column, so the prompt builder either should not have access to the histogram or should limit the number of arguments for the histogram to avoid this:
![image](https://github.com/AlexandreSajus/TalkToTaipy/assets/62465003/c5496da1-b815-40ab-aac1-f6c7f5e60e2c)

**Comment by thanhnew2001** [comment]
will fix this

**Comment by thanhnew2001** [comment]
I fixed it.

**Comment by AlexandreSajus** [comment]
Good one. A few things were missing to make this work, though:
[#91cd2027c37f79a18567b4d63338af51c96146e7](https://github.com/AlexandreSajus/TalkToTaipy/commit/91cd2027c37f79a18567b4d63338af51c96146e7)

I'll merge
