### ISSUE TITLE
UI pass

### ISSUE THREAD

**Issue by AlexandreSajus** [AlexandreSajus/TalkToTaipy#90]
We are going to make a UI pass on the app with the help of Joffrey.

The goal is mainly better font sizes (bigger and fewer uniforms across the app)
The user should not have to scroll to see the result of his prompt.

**Comment by JaufreyTpy** [comment]
# My UI/UX pass proposal

### Before
![image](https://github.com/AlexandreSajus/TalkToTaipy/assets/115568883/5ac3077c-8180-4979-b94d-7fcc8bc04376)

### After
By default
![image](https://github.com/AlexandreSajus/TalkToTaipy/assets/115568883/062f26dc-6093-45d6-a371-b3f702e3175b)
With expanded prompt help
![image](https://github.com/AlexandreSajus/TalkToTaipy/assets/115568883/3410719c-aa6a-4e69-8bd8-674e129bb6ee)
